### ISSUE TITLE
Exceptions after installing USync Forms 8.0.1.0

### ISSUE THREAD

**Issue by Sven883** [KevinJump/uSync.Forms#7]
Hello!

We recently installed USync Forms 8.0.1.0 on our project but we're getting errors now.
Info: 
- Umbraco version 8.14.0
- USync Forms version 8.0.1.0
- USync Complete version 8.11.4 (Paid license)

Any idea what the problem could be? Thanks!

```[BootFailedException: Boot failed: Umbraco cannot run. See Umbraco's log file for more details.

-> Umbraco.Core.Exceptions.BootFailedException: Boot failed.

-> System.Reflection.ReflectionTypeLoadException: Could not load all types from "uSync.Forms, Version=8.0.1.0, Culture=neutral, PublicKeyToken=null" due to LoaderExceptions, skipping:
. System.IO.FileNotFoundException: Could not load file or assembly 'Umbraco.Forms.Core, Version=8.8.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
. System.IO.FileNotFoundException: Could not load file or assembly 'Umbraco.Forms.Core, Version=8.8.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
. System.IO.FileNotFoundException: Could not load file or assembly 'Umbraco.Forms.Core, Version=8.8.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
. System.IO.FileNotFoundException: Could not load file or assembly 'Umbraco.Forms.Core, Version=8.8.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
. System.IO.FileNotFoundException: Could not load file or assembly 'Umbraco.Forms.Core, Version=8.8.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
. System.IO.FileNotFoundException: Could not load file or assembly 'Umbraco.Forms.Core, Version=8.8.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
. System.IO.FileNotFoundException: Could not load file or assembly 'Umbraco.Forms.Core, Version=8.8.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

   at Umbraco.Core.Composing.TypeFinder.GetTypesWithFormattedException(Assembly a) in D:\a\1\s\src\Umbraco.Core\Composing\TypeFinder.cs:line 569
   at Umbraco.Core.Composing.TypeFinder.GetClassesWithBaseType(Type baseType, IEnumerable`1 assemblies, Boolean onlyConcreteClasses, Func`2 additionalFilter) in D:\a\1\s\src\Umbraco.Core\Composing\TypeFinder.cs:line 504
   at Umbraco.Core.Composing.TypeFinder.FindClassesOfType[T](IEnumerable`1 assemblies, Boolean onlyConcreteClasses) in D:\a\1\s\src\Umbraco.Core\Composing\TypeFinder.cs:line 346
   at Umbraco.Core.Composing.TypeLoader.<>c__DisplayClass53_0`1.<GetTypes>b__1() in D:\a\1\s\src\Umbraco.Core\Composing\TypeLoader.cs:line 622
   at Umbraco.Core.Composing.TypeLoader.GetTypesInternalLocked(Type baseType, Type attributeType, Func`1 finder, String action, Boolean cache) in D:\a\1\s\src\Umbraco.Core\Composing\TypeLoader.cs:line 840
   at Umbraco.Core.Composing.TypeLoader.GetTypesInternal(Type baseType, Type attributeType, Func`1 finder, String action, Boolean cache) in D:\a\1\s\src\Umbraco.Core\Composing\TypeLoader.cs:line 741
   at Umbraco.Core.Composing.TypeLoader.GetTypes[T](Boolean cache, IEnumerable`1 specificAssemblies) in D:\a\1\s\src\Umbraco.Core\Composing\TypeLoader.cs:line 620
   at Umbraco.Core.Runtime.CoreRuntime.GetComposerTypes(TypeLoader typeLoader) in D:\a\1\s\src\Umbraco.Core\Runtime\CoreRuntime.cs:line 418
   at Umbraco.Core.Runtime.CoreRuntime.ResolveComposerTypes(TypeLoader typeLoader) in D:\a\1\s\src\Umbraco.Core\Runtime\CoreRuntime.cs:line 391
   at Umbraco.Core.Runtime.CoreRuntime.Boot(IRegister register, DisposableTimer timer) in D:\a\1\s\src\Umbraco.Core\Runtime\CoreRuntime.cs:line 179]
   Umbraco.Core.Exceptions.BootFailedException.Rethrow(BootFailedException bootFailedException) in D:\a\1\s\src\Umbraco.Core\Exceptions\BootFailedException.cs:80
   Umbraco.Web.Composing.<>c__DisplayClass4_0.<Init>b__0(Object sender, EventArgs args) in D:\a\1\s\src\Umbraco.Web\Composing\ModuleInjector.cs:44
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +201
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +132
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +73```

**Comment by KevinJump** [comment]
Hi, 

What version of Umbraco forms do you have installed ?

**Comment by Sven883** [comment]
Version 8.6.2 :-)

**Comment by KevinJump** [comment]
I think uSync.Forms requires Forms 8.8+ but i will double check.

**Comment by Sven883** [comment]
Would be weird, we have another project with the same umbraco forms version and there was no problem there.

**Comment by KevinJump** [comment]
yeah - its built against v8.8 - but it does appear to work lower versions (ideally forms v8.8 would be the version to run for this reason).

might be worth checking there are not other projects being built as part of the site that could be bringing in a diffrent umbraco forms version ? _(so if you have a library project with the site and that has a diffrent package version after the build the dll from that library might be the one in the site)._

I have just had it working now on a site with these package versions installed

```xml
  <package id="Umbraco.SqlServerCE" version="4.0.0.1" targetFramework="net472" />
  <package id="UmbracoCms" version="8.14.0" targetFramework="net472" />
  <package id="UmbracoCms.Core" version="8.14.0" targetFramework="net472" />
  <package id="UmbracoCms.Web" version="8.14.0" targetFramework="net472" />
  <package id="UmbracoForms" version="8.6.2" targetFramework="net472" />
  <package id="UmbracoForms.Core" version="8.6.2" targetFramework="net472" />
  <package id="uSync" version="8.10.4" targetFramework="net472" />
  <package id="uSync.BackOffice.Core" version="8.10.4" targetFramework="net472" />
  <package id="uSync.Community.Contrib" version="8.10.4" targetFramework="net472" />
  <package id="uSync.Complete" version="8.11.4" targetFramework="net472" />
  <package id="uSync.ContentEdition" version="8.10.4" targetFramework="net472" />
  <package id="uSync.Core" version="8.10.4" targetFramework="net472" />
  <package id="uSync.Expansions.Core" version="8.11.4" targetFramework="net472" />
  <package id="uSync.Exporter" version="8.11.4" targetFramework="net472" />
  <package id="uSync.Forms" version="8.0.1" targetFramework="net472" />
  <package id="uSync.History" version="8.10.4" targetFramework="net472" />
  <package id="uSync.PeopleEdition" version="8.11.4" targetFramework="net472" />
  <package id="uSync.Publisher" version="8.11.4" targetFramework="net472" />
  <package id="uSync.Snapshots" version="8.11.4" targetFramework="net472" />
```

**Comment by Sven883** [comment]
Found the problem! There was a problem with the reference of Umbraco Forms. Re-installing umbraco forms solved the problem. Thanks for the quick response!!
